name: Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-235-70-173.ap-south-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/soulspace
          git pull origin main
          sudo docker rm -f $(sudo docker ps -aq) || true
          sudo docker build -t whispr .
          sudo docker run -d --restart always --name whispr-container -p 3000:3000 whispr
        EOF
